from mcpi.minecraft import Minecraft
import time

mc=Minecraft.create()
pos=mc.player.getTilePos()
    
print('x=',pos.x,'y=',pos.y,'z=',pos.z)

for xz in range(30):
    x=pos.x+xz
    z=pos.z+xz
    mc.setBlock(x,pos.y,pos.z,89)
    mc.setBlock(pos.x,pos.y,z,89)
    
mc.setBlock(pos.x,pos.y,pos.z,1)
mc.setBlock(pos.x,pos.y+1,pos.z,4)
mc.setBlock(pos.x,pos.y+2,pos.z,4)
mc.setBlock(pos.x,pos.y+3,pos.z,4)
mc.setBlock(pos.x,pos.y+4,pos.z,4)
mc.setBlock(pos.x,pos.y+5,pos.z,5)
mc.setBlock(pos.x,pos.y+6,pos.z,6)
mc.setBlock(pos.x,pos.y+7,pos.z,17)
mc.setBlock(pos.x,pos.y+8,pos.z,42)
mc.setBlock(pos.x,pos.y+9,pos.z,19)
mc.setBlock(pos.x+5,pos.y,pos.z,100)
mc.setBlock(pos.x+5,pos.y+1,pos.z,139)
mc.setBlock(pos.x+5,pos.y+2,pos.z,233)
mc.setBlock(pos.x+5,pos.y+3,pos.z,1)
mc.setBlock(pos.x+5,pos.y+4,pos.z,69)
mc.setBlock(pos.x+5,pos.y+5,pos.z,2)
mc.setBlock(pos.x+5,pos.y+6,pos.z,1)
mc.setBlock(pos.x+5,pos.y+7,pos.z,1)
mc.setBlock(pos.x+5,pos.y+8,pos.z,1)
mc.setBlock(pos.x+5,pos.y+9,pos.z,1)
mc.setBlock(pos.x,pos.y,pos.z+5,1)
mc.setBlock(pos.x,pos.y+1,pos.z+5,3)
mc.setBlock(pos.x,pos.y+2,pos.z+5,3)
mc.setBlock(pos.x,pos.y+3,pos.z+5,3)
mc.setBlock(pos.x,pos.y+4,pos.z+5,3)
mc.setBlock(pos.x,pos.y+5,pos.z+5,3)
mc.setBlock(pos.x,pos.y+6,pos.z+5,1)
mc.setBlock(pos.x,pos.y+7,pos.z+5,1)
mc.setBlock(pos.x,pos.y+8,pos.z+5,1)
mc.setBlock(pos.x,pos.y+9,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+1,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+2,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+3,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+4,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+5,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+6,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+7,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+8,pos.z+5,1)
mc.setBlock(pos.x+5,pos.y+9,pos.z+5,1)
